package students.nikola_korovacka.lesson_12;

public class Task_17 {
    /*наследование от Exception в данном случае соответствует лучшей практике,
 так как отражает семантику ошибки и обеспечивает необходимость ее обработки в вызывающем коде.*/
}
